AllSpiceIO/py-allspice

- README.md
- __init__.py
- allspice/__init__.py
- allspice/allspice.py
- allspice/apiobject.py
- allspice/baseapiobject.py
- allspice/exceptions.py
- tests/conftest.py
- tests/test_api.py
- tests/test_api_longtests.py
Rename Gitea in all places where a user of the API would interact with AllSpice. Closes #1. 
A couple of notes:
1. I called the url `allspice_hub_url` instead of `allspice_url`,
2. Instead of calling the instance `allspice` I called it `allspice_client`,
3. In places where the code is talking about gitea I left it as is. 
These are not set in stone - if any of these seem like they're likely to cause confusion I can change that too.
> Rename Gitea across the API to AllSpice

- README.md
- allspice/allspice.py
- allspice/apiobject.py
- allspice/exceptions.py
- examples/generate_bom/README.md
- examples/generate_bom/generate_bom.py
- tests/test_api.py
Adds:
1. Functions for fetching objects generated by AllSpice, i.e. the JSON and SVG files for cad files. 
2. An example script for generating a BOM from a PrjPcb file 
3. A few convenience methods in the client that made it much easier to work with in scripts like the BOM script. 
Instead of writing a complete method for generating the BOM as we considered for #8, I think this approach works out better because the specific needs for generating a BOM could differ from client to client.
Closes #14. Also closes #8 (@danielallspice lmk if you think there's something else we can do here for #8!)
> Add client functions for AllSpice-generated objects and an example BOM Script

- __init__.py
- allspice/allspice.py
- allspice/apiobject.py
- examples/team_management/README.md
- examples/team_management/manage_teams.ipynb
- tests/test_api.py
Closes #7. This adds an example for managing teams with py-allspice in a Jupyter notebook format, along with a couple of small changes in team management for convenience.
> Create example for team management with py-allspice

- allspice/allspice.py
- allspice/apiobject.py
- tests/test_api.py
Adds the following functions:
- Create a new comment on an Issue
- Edit and delete comments
- Get attachments on a comment
- Edit and delete attachments
- Upload a new attachment to a comment
One caveat is that because Attachment objects don't carry all the information needed to edit or delete them, they are edited and deleted via `Comment.edit_attachment` and `Comment.delete_attachment` instead.
> Add client functions for comment and attachment APIs

- allspice/apiobject.py
- allspice/baseapiobject.py
- tests/test_api.py
Sorry for the kitchen sink PR - this includes:
1. Filtering options for issues, design reviews and commits
2. A refactor of the `commit` method for the API Objects which fixes committing multiple times in a repo sending excess data.
3. `get_branches` fetches all branches in a repo instead of just the first page.
4. Using strings for the `base` and `head` fields of Design Reviews, which fixes an issue when a design review is against/from a deleted branch, as can happen after a DR is closed.
> Multiple small fixes and improvements

- examples/README.md
- examples/check_parts_in_schematics/README.md
Sorry about this - didn't catch the typos until the release. I had to rename the script because I realized "Schematic Library" is a loaded term, but I forgot to make all the changes in readme and the index. This led to a few broken links which can be confusing.
> Fix links in the example README

- CHANGELOG.md
- allspice/apiobject.py
- tests/test_api.py
The major change for this release is BOM generation, but I'm also sneaking in a small change: `Team.add_repo` doesn't need an entire repo object, so we also take a string instead.
(Some whitespace changes snuck in because of my trim whitespace settings)
> Prep for v2.3.0 release

- CHANGELOG.md
- allspice/allspice.py
- allspice/apiobject.py
- setup.py
- tests/test_api.py
- tests/test_api_longtests.py
Fixes a reported issue where not all members of a team were being returned.
> Get all team members from paginated responses

- __init__.py
- allspice/apiobject.py
- allspice/utils/bom_generation.py
- tests/test_api.py
- tests/test_utils.py
Closes #60.
The `PrjPcb` can use `\n\r` for new lines instead of `\r\n`, which is what we expect. This PR changes the regex we use to support both (along with `\n`.) Additionally, while writing a test for this code, I updated a deprecated method to create branches.
> Broaden newline regex in Alitum BOM generation

- .github/workflows/test.yml
- .vscode/settings.json
- allspice/__init__.py
- allspice/allspice.py
- allspice/apiobject.py
- allspice/baseapiobject.py
- allspice/exceptions.py
- allspice/utils/bom_generation.py
- allspice/utils/netlist_generation.py
- examples/generate_bom/compute_cogs.py
- examples/generate_bom/generate_bom.py
- examples/generate_netlist/generate_netlist.py
- examples/topics/clone_all_repos_by_topic.py
- flake.nix
- pyproject.toml
- requirements-test.txt
- setup.py
- tests/conftest.py
- tests/test_api.py
- tests/test_api_longtests.py
- tests/test_api_ratelimiting.py
- tests/test_utils.py
This PR removes autopep8 and uses ruff instead for formatting checking in CI. We are already using ruff for linting, and it comes with a formatter, so we don't need to manage autopep8 for formatting. This change does lead to different formatting because ruff's is black-compatible.
> Remove autopep8 completely

- allspice/apiobject.py
- allspice/utils/bom_generation.py
- tests/test_api.py
- tests/test_utils.py
Closes #61. This endpoint method is simpler to use and doesn't require a base64 round trip when fetching a single file with a known path. This PR also removes the makeshift `_get_file_content` method used in BOM generation.
> Add API method to get the raw binary content of a single file

- allspice/apiobject.py
- tests/test_api.py
Closes #75. This also changes the `repo.create_release` method to make arguments that should've been optional actually optional. This was an oversight in the original releases PR.
> Add method to download release asset

- .vscode/settings.json
- allspice/apiobject.py
- tests/test_api.py
Closes #64.
This implements functions for all of the API endpoints that work with commit statuses. One caveat here is that the repo and owner for the commit is "deduced" from the URL of the commit, as this is faster and cheaper than requesting the owner when parsing the commit, or having the call site provide the repo.
> Add APIs to work with commit statuses

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- CHANGELOG.md
- setup.py
- tests/test_api.py
- Removes a deprecation warning from using ruff in the test workflow
- Removes dynamic insertion of a version into setup.py at tag time.
- Formatting changes in both workflow files
- Adds v2.5 changes to the changelog.
~~Stacked on #78 since the changelog assumes the optional args fix there.~~
> Prep for v2.5 release

- allspice/utils/bom_generation.py
- examples/generate_bom/generate_bom.py
- tests/data/archimajor_bom_expected.csv
- tests/data/archimajor_bom_hierarchical_expected.csv
- tests/test_utils.py
Closes #55.
This change removes the `pcbdoc_file` path from the `generate_bom_for_altium` util, and updates the logic to build and traverse the hierarchy of schdoc files instead. This is a breaking change, as the public api of the library has changed. This change also introduces the usage of `configparser` to read the PrjPcb file instead of using a regex, as this will be useful for future changes to the BOM generation. This is the first of three PRs that will change the BOM generation function. 
The test file has to be updated because the new method produces the CSV in a different order.
> Remove PCB from BOM generation

- examples/generate_bom/generate_bom.py
Using the custom action, it's not easy to omit an option. It's much easier to pass an empty string. This change makes it so that both omitted and empty string for group-by are treated the same.
> Fix to allow empty string for group by

- .github/workflows/deploy.yml
Closes #102. I haven't been able to test it for obvious reasons, but from the changelogs I don't see any changes that would break this workflow.
> Bump actions versions in deploy workflow

- .github/workflows/docs.yml
Fixes a run failure. This was a mistake due to an older version of pdoc - I'd fixed it when I tested the run locally but forgot to change it in the workflow file.
> Remove invalid flag from pdoc invocation

- allspice/apiobject.py
Fixes https://github.com/AllSpiceIO/py-allspice/issues/70.
This issue was caused by `Issue` fetching the repository every time it is initialized via `parse_response`. This leads to an N+1 query, which can be especially cumbersome when fetching all issues of a repository with many issues. This commit fixes that by propagating the repository from the caller of `Issue.parse_response`, and eager loading it only in cases where one issue at a time is loaded.
> Eliminate N+1 API requests in issues

- allspice/apiobject.py
- tests/test_api.py
Fixes https://github.com/AllSpiceIO/py-allspice/issues/81.
This avoids having to store the entire file in memory when downloading large files.
> Add API to stream file from repo

- README.md
Add a link to the built documentation originally introduced in #115.
You may want to also consider adding a website link to the repo.
> doc: Add link to built pdoc documentation

- .github/workflows/docs.yml
We shouldn't have to tag a release to deploy the docs every time. 
I don't like the [default permissions GitHub has for `workflow_dispatch`,](https://github.com/orgs/community/discussions/26622) but the write access requirement and the protection rule on the GitHub environment should keep us safe.
> Allow manual deploys to the docs

- .github/workflows/test.yml
- README.md
The CI typecheck script fails on any differences in the working directory, and is therefore sensitive to minor changes in the cassettes. We should not be failing of diffs in the cassettes for three reasons:
1. The changes are usually minor, such as in the headers, and we shouldn't be sensitive to those;
2. Changes that affect the logic will be tested in the API or Utils tests; and
3. Changes in the API responses that affect the attribute types will be highlighted by diffing the API object file alone.
Therefore, this commit:
1. Completely disables vcr.py in the scheduled tests so that the cassettes are not touched at all; and
2. Diffs only the apiobject.py file to check if the types have changed.
> Fix CI typecheck failure due to changed cassettes

- CHANGELOG.md
- allspice/__init__.py
- allspice/apiobject.py
- tests/test_api.py
It was possible for the `issue_comment` field of a comment on a DR to be a blank string instead of null, which broke the logic that found the associated repository for a comment, which is required for the routes involved in making attachments to comments.
I also bumped the version to tag a patch release with this, as it significantly helps out with a workflow that we're working on.
> Fix Design Review Comments not having an associated repo

- .github/workflows/test.yml
Dependabot only has a read token and can't post a comment. We could give it a write token, but I don't see why we'd want coverage comments on these PRs anyway, so I'm just skipping that step.
Stacked on #173.
> Skip coverage comment on dependabot PRs

- allspice/allspice.py
- allspice/apiobject.py
- tests/test_api.py
Closes ID-491. Already in use for where-used.
> Add endpoint to fetch git trees

- allspice/utils/bom_generation.py
- allspice/utils/list_components.py
As it turns out, System Capture BOM generation did not get the benefits of the changes in #157 as the functions for filtering and sorting rows were not called in the system capture BOM function. This was an entirely avoidable mistake as the logic for BOM generation for all formats is substantially the same. This commit moves the logic for BOM generation into the `generate_bom` function and makes the format specific functions aliases of the same. This should avoid similar mistakes in the future.
Closes ID-529.
> Refactor BOM generation to centralize logic

- allspice/utils/list_components.py
For some formats we end up interpreting some non-component elements on the board as components. These do not have any attributes and therefore add a blank row to the bom or an empty object to list_components.
However, since it is possible that there is a user error that leads to some components that shouldn't be blank end up being blank, a debug log has been added to catch that case. The log respects the level of the AllSpice client's logger, which is set to INFO by default.
Closes ID-513.
> Filter out blank components in list_components

- allspice/apiobject.py
- tests/test_api.py
The browser_download_url property of attachments can be confusing, as it is a full URL and `allspice.requests_get_raw` doesn't work with absolute URLs. The new `Attachment.download_to_file` method provides a "blessed" way to download the attachment.
> Add method to download an attachment

- allspice/apiobject.py
- requirements-test.txt
There were a few non-breaking additions to the API outputs in 1.22. This PR adds the type sigs for those, which also fixes CI failure with 1.22. Also, strictly specfies the version of `ruff` so we don't have CI break on unrelated PRs.
> Update type annotations for 1.22

- allspice/utils/list_components.py
- tests/test_utils.py
Earlier, we would retry forever if the JSON wasn't generated. This usually wasn't a problem because the JSON would eventually be generated *or* lead to a server error, but we've seen cases where this hasn't been true. Either way, we should've limited the number of retries, `list_components` just didn't count the number of attempts. This commit counts the attempts, stops at 5 retires, and tests this behavior.
> Enforce max retries in list_components

- allspice/utils/list_components.py
The previous limit of 5 seems too short for the CI environment, which suggests it will also be too short for some other resource-limited environments running Hub. Increase the limit to 10 to allow for bigger files to be generated.
Long term, we should absolutely make this configurable (along with the sleep times).
> Increase max retry count to 10 in list_components

- CHANGELOG.md
- allspice/__init__.py
This is 3.7.0 instead of 4.0.0 despite the potentially breaking nature of the max retries change because that was a bug, and always intended to fail after 5 attempts. However, if we feel like this is serious enough to merit a bump to 4 I can change this PR to do that.
> Bump version to 3.7.0

- allspice/apiobject.py
This should be a completely avoidable error with the type signatures we have, but there's a few reasons why it didn't show up. I'm thinking of a few solutions to those so we can avoid this sort of error in the future.
> Fix invalid arguments when committing releases and assets

- allspice/utils/list_components.py
- tests/test_utils.py
There is a daily CI failure as the CI server cannot generate JSONs in <5s every time. This PR allows py-allspice to keep retrying only when the tests are run without cassettes. As discussed before, ideally we'd have configurable retries, but we'd have to discuss how the configuration for that would look and it would require changes across the stack. This is good enough to get the CI to stop failing.
> Retry BOM gen tests up to 100 times when testing without cassettes

- allspice/allspice.py
Previously, the `log_level` argument to `AllSpice` didn't actually do anything. Since the logger doesn't have a specified handler, it falls back to the root logger which does not respect the result of `setLogLevel`. This commit actually creates a handler for the allspice client's logger, which enables `setLogLevel` to actually work.
> Create and use a log handler to actually set log level

- allspice/apiobject.py
This would allow enabling/disabling actions on a repository using:
```py
repo.has_actions = True # or false
repo.commit()
```
> Make `has_actions` patchable on Repository

- allspice/apiobject.py
- tests/test_api.py
`Issue.assets` is often not set, like in the common case when `Repository.get_issues` is used to fetch all issues. This meant that getting the assets on the issue itself required re-loading it with `Issue.request`, and there was no way to create an attachment on issue issue. This commit fixes both problems.
> Add method to get and create Issue attachments

- CHANGELOG.md
- allspice/__init__.py
* Add support for sdax variants when generating BOM by @jackHay22 in https://github.com/AllSpiceIO/py-allspice/pull/217
* Bump ruff from 0.8.4 to 0.9.9 by @dependabot in https://github.com/AllSpiceIO/py-allspice/pull/213
**Full Changelog**: https://github.com/AllSpiceIO/py-allspice/compare/v3.8.0...v3.9.0
> Bump version to 3.9.0

- .github/workflows/test.yml
* [Set incoming-webhook](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0#the-webhook-type-must-be-specified-for-incoming-webhooks)
* [Convert payload to yaml](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0#user-content-payloads-can-now-be-written-in-yaml)
> ci: fix slack send v2 breaking changes
